### ISSUE TITLE
[ros2run]: Segmentation fault

### ISSUE THREAD

**Issue by wxydejoy** [ros-drivers/usb_cam#225]
I tried to modify the configuration file and run it, but I encountered the following error. I tried to modify various parameters, but it did not solve the problem. Please help me solve the problem

## Terminal

```bash
$ ros2 run usb_cam usb_cam_node_exe --ros-args --params-file ./default_cam.yaml

[INFO] [1675744515.473145126] [usb_cam]: camera_name value: test_camera
[WARN] [1675744515.473206501] [usb_cam]: framerate: 30.000000
[INFO] [1675744515.473927872] [usb_cam]: camera calibration URL: package://usb_cam/config/camera_info.yaml
[INFO] [1675744515.474210505] [usb_cam]: Starting 'test_camera' (/dev/video0) at 1280x720 via mmap (mjpeg, yuv422p) at 30 FPS
[ros2run]: Segmentation fault
```
## default_cam.yaml
```yaml
/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg"
      color_format: "yuv422p"
      image_width: 1280
      image_height: 720
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"

```

## v4l2-ctl -d /dev/video0 --list-formats-ext

```bash
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.067s (15.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.067s (15.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)



```
